import { Source_Serif_4 } from "next/font/google";
import "./globals.css";

const sourceSerif4 = Source_Serif_4({ subsets: ["latin"] });

export function getStaticProps() {}

export const metadata = {
  title: "Booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceSerif4.className}>{children}</body>
    </html>
  );
}
